output = "db/models"
wipe = true
no-tests = true
add-enum-types = true
pkgname = "dbmodels"
add-global-variants = true

[psql]
dbname = "postgres"
host = "localhost"
port = 5432
user = "postgres"
pass = "postgres"
sslmode = "disable"
